### ISSUE TITLE
Output networkx topology in a spatial form

### ISSUE THREAD

**Issue by sethfitz** [open-reblock/topology#7]
GeoJSON is best, Shapefile is fine.

This enables the resulting network to be displayed using typical web map tools.

**Comment by joehand** [comment]
Related, make sure we can output intermediate stages in the same format. (#8)

**Comment by brelsford** [comment]
the pull request I submitted fixes this issue.

**Comment by joehand** [comment]
Do we need to have the projection as part of the geoJSON output or should/can we add that later?

**Comment by brelsford** [comment]
Carlos said they'd do that part in the local code module, and he doesn't need it as an export.
